### ISSUE TITLE
installation questions

### ISSUE THREAD

**Issue by edult** [level09/enferno#13]
I am trying to install package. Getting some issues. It cannot find the files, but they are all there. What do you think is the issue?

Thanks

(venv)user@user-HP-Stream-Notebook-PC-11:/media/user/MICROSD/Linux/enferno/enferno$ flask install
Traceback (most recent call last):
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/flask/cli.py", line 478, in main
    cli.main(args=args, prog_name=name)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/flask/cli.py", line 316, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/flask/cli.py", line 209, in load_app
    rv = locate_app(self.app_import_path)
  File "/media/user/MICROSD/Linux/enferno/enferno/venv/lib/python3.4/site-packages/flask/cli.py", line 89, in locate_app
    __import__(module)
  File "/media/user/MICROSD/Linux/enferno/enferno/enferno.py", line 7, in <module>
    from app import create_app
ImportError: No module named 'app'

(venv)user@user-HP-Stream-Notebook-PC-11:/media/user/MICROSD/Linux/enferno/enferno$ echo $PYTHONPATH
.

tree -L 1
.
├── app.py
├── commands.py
├── enferno.py
├── extensions.py
├── gulpfile.js
├── __init__.py
├── node_modules
├── package.json
├── public
├── __pycache__
├── README.rst
├── requirements.txt
├── script.py
├── settings.py
├── static
├── tasks.py
├── templates
├── user
└── venv

**Comment by level09** [comment]
Hi @edult , Are you using the master branch (Mongodb) ? or the sql alchemy branch ? 

Did you export the App variable before running flask install ?
