### ISSUE TITLE
Registration problem: SMTPAuthenticationError: (535, '5.7.0 Mailgun is not loving your login or password

### ISSUE THREAD

**Issue by scheung38** [level09/enferno#7]
Upon launching and going to the registration endpoint to create a new user, I can see in PyCharm Mongo Explorer a new collection created with email, and password(hasded), but browser returns exception and I cannot go any further:

```
Traceback (most recent call last):
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_security/decorators.py", line 205, in wrapper
    return f(*args, **kwargs)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_security/views.py", line 117, in register
    user = register_user(**form.to_dict())
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    user=user, confirmation_link=confirmation_link)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_security/utils.py", line 333, in send_mail
    mail.send(msg)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/home/osboxes/anaconda/envs/venv/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.0 Mailgun is not loving your login or password')
```

But trying the already login details it does take me to User Account:

Welcome, foo_bar@yahoo.com

Last login at: 2015-09-21 11:04:14.260000

Logout

or do I need to change settings.py? Not sure how to configure it:

```
    #flask mail settings - Mailgun
    MAIL_SERVER = 'smtp.mailgun.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
    MAIL_USERNAME = 'user'
    MAIL_PASSWORD = 'pass'
    SECURITY_EMAIL_SENDER = 'info@level09.com'
```

**Comment by level09** [comment]
Hi @scheung38 , 
Please check the settings.py and update the SMTP Mail settings: 

https://github.com/level09/enferno/blob/master/settings.py#L32

By default the smtp is not activated as the values are temporary. 

You can set those to your own smtp credentials and the emails should work fine, you could try your Gmail credentials if you would like a quick way to test it.

**Comment by scheung38** [comment]
Hi, Thanks for immediate response, so like this?:
```
    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
    MAIL_USERNAME = 'user'
    MAIL_PASSWORD = 'pass'
    SECURITY_EMAIL_SENDER = 'seb@yahoo.com'
```

**Comment by level09** [comment]
Yes, 
for the user : it would be your_user@gmail.com 
and SECURITY_EMAIL_SENDER = 'your_user@gmail.com'

That should work fine.

**Comment by scheung38** [comment]
Sorry I dont understand, user as in:
```
 MAIL_USERNAME = 'user'
```
?

**Comment by level09** [comment]
if you are using your Gmail details, the username should be your full Gmail address for example : 
scheung38@gmail.com , the password should be your Gmail password. 

the 'user' and 'pass' are just placeholders and you should replace them with your own strings.

**Comment by scheung38** [comment]
Ok will try, but email settings should not be the cause of the above error? So email is entered for both MAIL_USERNAME as well as SECURITY_EMAIL_SENDER?

**Comment by level09** [comment]
well, you will have to set those settings the same way you set other settings like database configurations, redis etc .. 

the mail username is the smtp username, while the security email sender is the email used to send website emails (usually it is from the same domain). 

if you prefer you could sign up for a free mailgun account and they will give you a generous offer for sending emails for free using smtp credentials.

**Comment by scheung38** [comment]
I can successfully Register a new user, can see with Pycharm Mongo Explorer a new user has been created, but I have no idea why the response in chrome says:
```
smtplib.SMTPAuthenticationError
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsVY\n5.7.14 9v3vN9MX6DCFzAUhHTg75r5qfk5GksNK6IAV0yy9ZmLbLCHrgZwGmReX4XJxdpthrdfSys\n5.7.14 c2Lp998SqbcU4nDkde5BpMKWfWJUvw9A0Ll0EFW6Vj4T5DDPKB-jeSaq7LKPGWQrJ1nSVv\n5.7.14 c_kV8MlYVn5k0iEGpqRPyOecXkg9XjidlByq9CrI3bssve7ti19CBKvs2k4cWKzwQmnsf4\n5.7.14 2TUKJ_0fuDNu-jTNFxFdo3Xw58ac> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 z2sm354629wij.1 - gsmtp')
```

**Comment by tejaswinichile** [comment]
@scheung38 Are you able to resolve the issue? If not please follow this :  https://support.google.com/accounts/answer/6010255
